development:
  DB_DATABASE: share-link
  DB_USERNAME: postgres
  DB_PASSWORD: root
  DB_HOST: localhost

production:
  DB_DATABASE: df5196seigopg8
  DB_USERNAME: fusmkgabchaavs
  DB_PASSWORD: 3a115e0147d6ee6bbe75111b09e8bb30982fe86d63e6c7c6af91745a384bbf18
  DB_HOST: ec2-52-19-170-215.eu-west-1.compute.amazonaws.com
  DB_URL: postgres://fusmkgabchaavs:3a115e0147d6ee6bbe75111b09e8bb30982fe86d63e6c7c6af91745a384bbf18@ec2-52-19-170-215.eu-west-1.compute.amazonaws.com:5432/df5196seigopg8
